// <auto-generated />
namespace BabyToys.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class cap_nhat_khachhang_user : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cap_nhat_khachhang_user));
        
        string IMigrationMetadata.Id
        {
            get { return "201312120244216_cap_nhat_khachhang_user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
