// <auto-generated />
namespace BabyToys.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class add_mail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_mail));
        
        string IMigrationMetadata.Id
        {
            get { return "201412010822585_add_mail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
